### ISSUE TITLE
Instant disconnect on presenting invalid evidence

### ISSUE THREAD

**Issue by in1tiate** [AttorneyOnline/tsuserver3#101]
**Steps to reproduce:**
  - You will need two clients to trigger this. Connect both of your clients to the same server.
  - Move both clients to the same area and make sure they are both CM.
  - With either client, create a new piece of evidence, select it, and activate the present button. **Do not send a message yet.**
  - With the other client, delete the evidence. There should not be any evidence now.
  - Notice on the first client that the present button is still activated despite there being no evidence in the area. Send a message while keeping the present button activated.

**Expected result:**
It should either not be possible to select invalid evidence, or the server should simply strip the evidence from the message before sending it.

**Actual result:**
The client that tried to present the evidence will be immediately disconnected from the server, and the message will not be sent.

**Note:**
This is a joint issue - while the client should not allow the user to present invalid evidence, tsuserver should be able to handle this case more elegantly.

**Comment by caleb-mabry** [comment]
If you try to reproduce this with the 2.8.5 client, it will not cause them to crash, however, there is still an issue that arises.
The traceback for the issue points to `net_cmd_ms` and refers to
```py
        # Reveal evidence to everyone if hidden
        if evidence:
            if self.client.area.evi_list.evidences[
                    self.client.evi_list[evidence] - 1].pos != 'all':
                self.client.area.evi_list.evidences[
                    self.client.evi_list[evidence] - 1].pos = 'all'
                self.client.area.broadcast_evidence_list()
```
Line 575 is the failing line `self.client.evi_list[evidence] - 1].pos != 'all':`
