### ISSUE TITLE
Error updating evidence

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/tsuserver3#106]
Discovered during 2.8 launch.

Backtrace:
```
 [events] aoprotocol@675 : Exception while running a command
 Traceback (most recent call last):
   File "/app/server/network/aoprotocol.py", line 670, in net_cmd_ct
     getattr(commands, called_function)(self.client, arg)
   File "/app/server/commands/character.py", line 52, in ooc_cmd_pos
     client.change_position(arg)
   File "/app/server/client_manager.py", line 543, in change_position
     self.area.update_evidence_list(self) #Receive evidence
 AttributeError: 'Area' object has no attribute 'update_evidence_list'
```

**Comment by caleb-mabry** [comment]
@oldmud0 
Do we have a way to replicate this issue? Honestly [the commit that references this issue](https://github.com/AttorneyOnline/tsuserver3/commit/7c97855b4e8069d53ae2a2cd486a0bd97c4cd256) Seems to have fixed the backtrace that you're showing. 

This issue looks like it might be dead in the water

**Comment by oldmud0** [comment]
Yeah I think this was supposed to be auto-closed.
