### ISSUE TITLE
Additive text allows adding to other people's text

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/tsuserver3#108]
**Expected behavior:** When someone other than me speaks, the "Additive" text option should have no effect.

**Actual behavior:** When someone other than me speaks, I can use the "Additive" text option to add more text to their chatbox, even though I have no control over their character.

**Fix:** Track character ID of who said the last message. Ignore additive option if the last message's character ID does not match that of the incoming message.

**Comment by Crystalwarrior** [comment]
oops, forgot to add that check to the protocol

**Comment by caleb-mabry** [comment]
You can make a class variable and use a class method to track the previous char_id that has sent the message
