### ISSUE TITLE
Emote modifier needs to be validated to prevent denial of service

### ISSUE THREAD

**Issue by mposs00** [AttorneyOnline/tsuserver3#112]
See [related client issue](https://github.com/AttorneyOnline/AO2-Client/issues/252)
This hang needs to be fixed client side, but older clients will still be susceptible, so the server should have logic to detect any emote modifier other than 0,1,2,5,6 and throw it out otherwise.

**Comment by oldmud0** [comment]
Already done:
https://github.com/AttorneyOnline/tsuserver3/blob/fefe5b008530c9f22d28c481b0ea95534f5cf66b/server/network/aoprotocol.py#L481-L482
The new rule is that 4 should not be allowed or replaced with 6.

**Comment by mposs00** [comment]
Replace it with 6, because outdated clients will be sending 4. Just silently swap with 6 and get on with life.
