### ISSUE TITLE
RuntimeError Invalid asyncio closure when Ctrl+C-ing on Ubuntu

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/tsuserver3#117]
![изображение](https://user-images.githubusercontent.com/3470436/90955395-dd220900-e485-11ea-8b36-78247a000119.png)

Doesn't occur on Windows with Ctrl+Pause Break method

**Comment by Crystalwarrior** [comment]
Also, Ctrl+Z on Ubuntu holds up the sockets until they're manually killed. Intentional?

**Comment by oldmud0** [comment]
Boring. Of course tasks are going to be destroyed when pending after a KeyboardInterrupt kills the event loop. This doesn't look like it affects anything. If you want you can wrap with some kind of interrupt handler but I don't really think it's necessary.
