### ISSUE TITLE
Ampersand breaks characters.yaml

### ISSUE THREAD

**Issue by collinxchu** [AttorneyOnline/tsuserver3#124]
Specifically, the & symbol universally breaks the yaml and cuts whatever slot it is short. I've attempted "Quotes", escaping the character with \\, and neither stops it from cutting the character slot short at the &.

To reproduce: Make a characters.yaml, put & anywhere in that particular line, and behold as when you start the server that it cuts the name short immediately before the &.

**Comment by oldmud0** [comment]
Oh, that's not a characters.yaml parsing bug. That's a server bug from not escaping special protocol characters correctly before sending the list. A workaround for now would be to use `<and>` explicitly in the characters.yaml file.

**Comment by caleb-mabry** [comment]
@oldmud0 
Is there anything I need to do to get #142 to be merged so we can close this issue?
Seems like the fix was merged into the client.
