### ISSUE TITLE
LE packet sends unescaped # and %

### ISSUE THREAD

**Issue by stonedDiscord** [AttorneyOnline/tsuserver3#130]
so if someone adds a URL to evidence description it will break the evidence in that area

**Comment by oldmud0** [comment]
I thought this was already fixed... how many times does evidence have to be fixed...

**Comment by caleb-mabry** [comment]
@stonedDiscord 

I'm not sure that I can replicate that issue right now. I've created evidence with a URL in the description and all of the other pieces of evidence that I have created seem fine.
![image](https://user-images.githubusercontent.com/36182383/105619883-f2002100-5dc4-11eb-8537-f66c7f31b635.png)
