### ISSUE TITLE
Characters unshown after loading localhost, courtroom hidden + emotes broken

### ISSUE THREAD

**Issue by duckduckstab1** [AttorneyOnline/tsuserver3#182]
Bug when you try to open up localhost on ace attorney online theres no characters, the courtroom is hidden, the emotes are broken.
Image link:
[https://i.imgur.com/lOb523s.png](https://i.imgur.com/lOb523s.png)

**Comment by duckduckstab1** [comment]
Fixed link bug.

**Comment by stonedDiscord** [comment]
which character did you pick

![grafik](https://user-images.githubusercontent.com/10584181/118851763-66aa1e80-b8d2-11eb-8103-3c367a57e76c.png)
this comes before the "No emote"

**Comment by duckduckstab1** [comment]
Possibly no idea

**Comment by duckduckstab1** [comment]
Maybe Butz.

**Comment by duckduckstab1** [comment]
This shows as no emote due to a code error from Github.

**Comment by stonedDiscord** [comment]
it seems like you've set a character and background in the settings that do not exist on the content repo

i suggest you get started with the client version if you want to start a server

https://aceattorneyonline.com/#download

**Comment by duckduckstab1** [comment]
No, I picked vanilla.

**Comment by oldmud0** [comment]
Huh?

I need network logs, please (open developer tools with F12 and go to the network tab).

**Comment by duckduckstab1** [comment]
This issue is closed due to low end scripts are behind the issues causing a memory leak.
