### ISSUE TITLE
How to use music?

### ISSUE THREAD

**Issue by PatrickHengy** [AttorneyOnline/tsuserver3#199]
Does anyone know why the server uses sound files and stuff normally but doesn't use the music in the Vanilla AO Client? It just says missing when trying to play it.

**Comment by Salanto** [comment]
You can add your own music to the musiclist in music.yaml.
The client music is stored in base/sounds/music

If it says missing it could not locate the file on your local client and the song. This message is from your client, not the server.
Please check your file names and extensions before opening an issue.

**Comment by PatrickHengy** [comment]
Thank you for the prompt response!
