### ISSUE TITLE
Server goes unlisted from master server sometimes

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/tsuserver3#29]
Unsure what's going on, but it seems the server will randomly drop connection with the master server and appear unlisted. Needs looking into.

**Comment by oldmud0** [comment]
Yes, it really does need looking into. Might need to overhaul the logging system to investigate the issue.

**Comment by mposs00** [comment]
Is this remedied with ms2?

**Comment by oldmud0** [comment]
I do believe so, but in rare occasions, the master server advertiser thread will die with no way to bring it back, or it will split into two advertiser threads advertising at the same time. I haven't received any more reports though.
