### ISSUE TITLE
TCP Ports used by tsuserver3 are never unbound on the VPS

### ISSUE THREAD

**Issue by Crystalwarrior** [AttorneyOnline/tsuserver3#36]
/title, it seems that every time I close the server and try to host it on the same IP again I get this message:
![default](https://user-images.githubusercontent.com/3470436/43681006-7da29810-9850-11e8-9afe-878ff9346e91.png)
The server is running on windows server 2012 R2. Any ideas as to why or how this is occuring?

I had to change the server ports about 5 times in the past week and the previously used ports are _still_ unusable.

**Comment by oldmud0** [comment]
@Crystalwarrior Sorry for my untimeliness, but are you still having this issue? There must be Python processes still lingering in the background.

**Comment by Crystalwarrior** [comment]
Yup. I'm unable to close those python processes myself due to permissions on the server machine.

**Comment by oldmud0** [comment]
Huh? That implies that the processes are not owned by your user.

**Comment by Parazoid** [comment]
Why is this still open?
@Crystalwarrior Did you ever fix it?

**Comment by oldmud0** [comment]
Let us know if you ever have problems again...
