### ISSUE TITLE
Can't get HDID of a banned player

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/tsuserver3#37]
The `Connected. HDID: {}` message is logged too late, which renders it impossible to get the HDID of a player that is allegedly banned.

**Comment by perplexedMurfy** [comment]
Would we also want to log the IPID and ban reason along with the HDID when a banned client attempts to connect?

**Comment by oldmud0** [comment]
Sure.

**Comment by oldmud0** [comment]
Closed: https://gitlab.com/AttorneyOnline/tsuserver3/issues/37
