### ISSUE TITLE
Web Clients cant join

### ISSUE THREAD

**Issue by Enovale** [AttorneyOnline/tsuserver3#38]
((should have enhancement tag))
Web clients cant join tsuserver servers and its the only thing preventing this server from being better than serverD, because many players come from the web client. Any way to add this manually or can this be added in an update? or is it already added and im stupid?

**Comment by Trey722** [comment]
It is already added (module websocket.py) but you’re not necessarily stupid.

Many things could cause web clients to fail connecting so you should probably get help in the [AO discord](https://discord.gg/PGupmrN) for this issue

**Comment by ghost** [comment]
It is already added (websocket.py module) but that doesn’t necessarily mean you’re stupid.

Many things could cause webclients to fail connecting so you should probably get help at the [AO Discord](https://discord.gg/PGupmrN) for this issue
