### ISSUE TITLE
/refresh should refresh areas as well

### ISSUE THREAD

**Issue by oldmud0** [AttorneyOnline/tsuserver3#45]
Areas and area permissions are not being refreshed by /refresh. According to a user, this is a regression from the previous version.

**Comment by Parazoid** [comment]
It doesn't seem to be a regression, fairly certain it wasn't a thing to begin with.

**Comment by oldmud0** [comment]
You're right but I guess it should now

**Comment by oldmud0** [comment]
More info: https://gitlab.com/AttorneyOnline/tsuserver3/issues/45

**Comment by oldmud0** [comment]
Too complicated of a feature.
