### ISSUE TITLE
Unable to start server due to AttributeError

### ISSUE THREAD

**Issue by EditFox** [AttorneyOnline/tsuserver3#51]
After following the instructions given in the readme, I get this error when trying to run start_server.py
`module 'server.database' has no attribute 'log_misc'`
I have Python 3.6.3 with Anaconda installed, Windows 10 x64, and I've installed the requirements.txt file.

**Comment by oldmud0** [comment]
The requirements have changed. You need Python 3.7. Or try installing dataclasses from pip - maybe that will fix it.

**Comment by EditFox** [comment]
Installing dataclasses manually did not work, but updating to Python 3.7+ did work for me. Thank you!
