### ISSUE TITLE
Uncaught IndexError on attempting to join full server

### ISSUE THREAD

**Issue by Chrezm** [AttorneyOnline/tsuserver3#64]
If the server is completely full (number of players == player limit), a new client attempting to join will trigger an IndexError due to heappop trying to pop off an empty client ID list. While it does correctly prevent the new client from joining, having an uncaught IndexError on console is probably not the intended outcome. Easiest to test by setting the player limit to a low number like 0 or 1.
Server still correctly responds to packets sent from other clients.

**Comment by oldmud0** [comment]
I remember documenting somewhere that the player limit is not enforced, but if it surpasses that limit, then bad things will happen. This is that bad thing.

**Comment by Chrezm** [comment]
The main reason why this is a problem is that the only way a potential client will know how many players are there is by clicking on the server in lobby, which in turn instantiates a Client object and takes on a client ID. There is no way for a client to be polite and ask if the server is full beforehand, so even a well-intentioned player can unknowingly raise this issue.
