### ISSUE TITLE
Server doesn't appear on mastersever list

### ISSUE THREAD

**Issue by Hefaustas** [AttorneyOnline/tsuserver3#68]
I enabled it, set the port and everything right, port forwarded and the server works ok, except it's not listed in the masterserver. Any way to fix this?

**Comment by stonedDiscord** [comment]
did you set this line to true
https://github.com/AttorneyOnline/tsuserver3/blob/e337c87551db1f7d4919041646557123a0fb1750/config_sample/config.yaml#L45
also you can't name it "My First Server"

**Comment by Parazoid** [comment]
Use the [discord](https://discord.gg/Ht3zKEy) for tech support on server issues.
